apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: trackingcovid.com
  namespace: covid
spec:
  secretName: trackingcovid-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.trackingcovid.com"
  dnsNames:
    - trackingcovid.com
    - "*.trackingcovid.com"
